Repository CodeitPart3/thejulge, pull requests merged in 2025-05, with the labels that each got.

#52 [feat] 내 프로필 페이지 구현 (/profile)
  src/Router.tsx
  src/components/Table.tsx
  src/layouts/MainLayout.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/ProfileCard.tsx
  src/pages/ProfilePage/components/UserApplicationTable.tsx
  src/pages/ProfilePage/components/UserApplicationTableSkeleton.tsx
  src/pages/ProfilePage/hooks/useUserApplications.ts
  src/pages/ProfilePage/loader/profileLoader.ts
  src/styles/utilities.css
Labels: Feature (기능 추가)

#59 [feat] 가게 등록 페이지 구현 (/shop/register)
  src/Router.tsx
  src/assets/icon/camera.svg
  src/components/Button.tsx
  src/layouts/MainLayout.tsx
  src/pages/ShopRegisterPage.tsx
  src/utils/number.ts
Labels: Feature (기능 추가)

#53 [feat] 모달 공통 컴포넌트 분리 및 레이아웃 구조화
  src/App.tsx
  src/components/Modal/AlertModalLayout.tsx
  src/components/Modal/ConfirmModalLayout.tsx
  src/components/Modal/Modal.tsx
  src/components/index.ts
  src/store/useModalStore.ts
  src/types/svg.d.ts
  tsconfig.json
Labels: Feature (기능 추가)

#69 [feat] 공고 상세 페이지 (알바생) 구현
  src/Router.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/constants/router.ts
  src/pages/NoticeEmployeePage.tsx
  src/pages/NoticeEmployeePage/NoticeEmployeePage.tsx
  src/pages/NoticeEmployeePage/components/NoticeDetailInfo.tsx
  src/pages/NoticeEmployeePage/components/ShopInfoPostCardSkeleton.tsx
  src/pages/NoticeEmployeePage/loader/noticeEmployeeLoader.ts
Labels: Feature (기능 추가)

#66 [feat] 로그인 페이지 구현 (/signin)
  src/hooks/useUserStore.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
Labels: Feature (기능 추가)

#71 [feat] 공고 등록 페이지 구현
  package-lock.json
  package.json
  src/pages/NoticeRegisterPage.tsx
Labels: Feature (기능 추가)

#68 [feat] 프로필 등록 페이지 구현
  src/Router.tsx
  src/pages/ProfileRegisterPage.tsx
  src/utils/phoneNumber.ts
Labels: Feature (기능 추가)

#72 [feat] 가게 정보 편집 페이지 구현
  src/assets/icon/camera.svg
  src/constants/shopCategory.ts
  src/pages/ShopEditPage.tsx
  src/pages/ShopRegisterPage.tsx
Labels: Feature (기능 추가)

#74 [feat] 프로필 편집 페이지 구현
  src/pages/ProfileEditPage.tsx
Labels: Feature (기능 추가)

#75 [feat] 공고 편집 페이지 구현
  src/pages/NoticeEditPage.tsx
  src/pages/ShopRegisterPage.tsx
Labels: Feature (기능 추가)

#79 [feat] 등록, 편집 페이지에 모달 적용
  src/pages/NoticeEditPage.tsx
  src/pages/NoticeRegisterPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileRegisterPage.tsx
  src/pages/ShopEditPage.tsx
  src/pages/ShopRegisterPage.tsx
Labels: Feature (기능 추가)

#77 [feat] 내 가게 페이지 구현
  src/Router.tsx
  src/pages/ShopPage.tsx
  src/pages/ShopPage/ShopPage.tsx
  src/pages/ShopPage/hooks/useShopData.ts
Labels: Feature (기능 추가)

#55 [feat] Dropdown 공통 컴포넌트 개발
  src/components/Dropdown/AlarmDropdownContent.tsx
  src/components/Dropdown/DropdownPopover.tsx
  src/components/Dropdown/FilterDropdownContent.tsx
  src/store/useAlarmStore.ts
  src/store/useFilterStore.ts
Labels: Feature (기능 추가)

#83 [feat] 프로필 미 등록 사용자, 공고 지원 시 프로필 등록 확인 모달 렌더링, 프로필 페이지 userId 적용
  src/components/NoticeDetailInfo/NoticeEmployeeActionButton.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/hooks/useUserApplications.ts
  src/pages/ProfilePage/loader/profileLoader.ts
Labels: Feature (기능 추가)

#84 [feat] Alert 컴포넌트 구현
  src/components/Alert/Alert.tsx
  src/components/Alert/AlertCard.tsx
  src/components/Alert/hooks/useAlarm.ts
  src/hooks/useIntersection.ts
  src/hooks/useOutsideClick.ts
  src/layouts/Header.tsx
  src/layouts/MainLayout.tsx
  src/utils/datetime.ts
Labels: Feature (기능 추가)

#88 [fix] 통합 테스트 전 공고 상세 (사장님, 알바생) 페이지 수정사항
  src/components/NoticeDetailInfo/NoticeEmployeeActionButton.tsx
  src/pages/NoticeEmployerPage/NoticeEmployerPage.tsx
Labels: Bug Fix (버그 수정)

#89 [fix] 등록, 편집 페이지 수정 사항
  src/pages/NoticeEditPage.tsx
  src/pages/NoticeRegisterPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileRegisterPage.tsx
  src/pages/ShopEditPage.tsx
  src/pages/ShopRegisterPage.tsx
Labels: Bug Fix (버그 수정)

#91 [feat] 공고 검색 페이지 구현
  src/Router.tsx
  src/components/SearchInput.tsx
  src/constants/router.ts
  src/layouts/Header.tsx
  src/pages/NoticeSearchPage/NoticeSearchPage.tsx
  src/pages/NoticeSearchPage/TotalNoticeSectionCopy.tsx
  src/pages/NoticeSearchPage/constantsCopy.ts
Labels: Feature (기능 추가)

#100 [fix] 공고 리스트 페이지 수정
  src/Router.tsx
  src/components/Dropdown/DropdownPopover.tsx
  src/components/Post/PostListSlider.tsx
  src/hooks/useNoticeList.ts
  src/pages/NoticeListPage/CustomNoticeSection.tsx
  src/pages/NoticeListPage/NoticeListPage.tsx
  src/pages/NoticeListPage/TotalNoticeSection.tsx
Labels: Bug Fix (버그 수정)

#96 [feat] 404 페이지 구현
  src/Router.tsx
  src/constants/router.ts
  src/layouts/Footer.tsx
  src/pages/NotFoundPage.tsx
  src/utils/number.ts
Labels: Feature (기능 추가)

#97 [feat] PageErrorElement 구현 및 적용
  src/Router.tsx
  src/components/PageErrorElement.tsx
  src/pages/ProfilePage/ProfilePage.tsx
Labels: Feature (기능 추가)

#98 [fix] 공고 카드 컴포넌트 수정사항
  public/default-image.png
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
Labels: Bug Fix (버그 수정)

#101 [fix] 내 가게 페이지 수정사항
  src/pages/ShopPage/ShopPage.tsx
Labels: Bug Fix (버그 수정)

#104 [fix] 공고 카드 컴포넌트 추가 수정
  src/components/Post/Post.tsx
Labels: Bug Fix (버그 수정)

#111 [feat] 공고 리스트 상세 필터 기능 구현
  src/components/Dropdown/FilterDropdownContent.tsx
  src/components/NoticeSearchResultHeader.tsx
  src/hooks/useNoticeList.ts
  src/pages/NoticeListPage/NoticeListPage.tsx
  src/pages/NoticeSearchPage/NoticeSearchPage.tsx
Labels: Feature (기능 추가)

#121 [fix] 내 프로필 페이지 버그 수정
  src/components/EmptyStateCard.tsx
  src/components/StatusBadge.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/ProfileCard.tsx
Labels: Bug Fix (버그 수정)

#124 [chore] favicon 및 타이틀 설정
  index.html
  public/tjg_favicon.png
Labels: Configuration (환경 설정)

#123 [fix] 공고 상세 페이지 (알바생, 사장님) 버그 수정
  src/components/NoticeDetailInfo/NoticeDetailInfo.tsx
  src/components/NoticeDetailInfo/NoticeEmployerActionButton.tsx
  src/pages/NoticeEmployeePage/NoticeEmployeePage.tsx
  src/pages/NoticeEmployerPage/NoticeEmployerPage.tsx
  src/pages/NoticeEmployerPage/components/NoticeApplicationTable.tsx
Labels: Bug Fix (버그 수정)

#129 [fix] 로그인, 회원가입 페이지 버그 수정
  src/Router.tsx
  src/layouts/AuthLayout.tsx
  src/pages/AuthPage/SigninPage.tsx
  src/pages/AuthPage/SignupPage.tsx
  src/pages/AuthPage/components/Spinner.tsx
  src/pages/AuthPage/hooks/useAuthForm.ts
Labels: Bug Fix (버그 수정)

#132 [fix] 내 가게 페이지 버그 수정
  src/components/Post/PostCard.tsx
  src/pages/ShopPage/ShopPage.tsx
Labels: Bug Fix (버그 수정)

#131 [fix] 상세 필터 및 Alert 컴포넌트 버그 수정
  src/components/Alert/Alert.tsx
  src/components/Alert/AlertCard.tsx
  src/components/Alert/hooks/useAlerts.ts
  src/components/Dropdown/FilterDropdownContent.tsx
  src/components/NoticeSearchResultHeader.tsx
  src/hooks/useBreakpoint.ts
  src/hooks/useIntersection.ts
  src/hooks/useRemoveTopPageScroll.ts
  src/utils/debounce.ts
  src/utils/device.ts
Labels: Bug Fix (버그 수정)

#133 [fix] 공고 컴포넌트 버그 수정
  src/components/Post/Post.tsx
  src/utils/datetime.ts
Labels: Bug Fix (버그 수정)

#113 [fix] 공고 리스트 UI 수정
  src/components/NoticeSearchResultHeader.tsx
  src/components/Post/PostListSlider.tsx
  src/components/SearchInput.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/pages/NoticeListPage/CustomNoticeSection.tsx
  src/pages/NoticeListPage/NoticeListPage.tsx
  src/pages/NoticeSearchPage/NoticeSearchPage.tsx
  src/styles/utilities.css
Labels: UI/UX (스타일 변경)

#134 [fix] Select 컴포넌트 버그 픽스
  src/components/Select.tsx
Labels: Bug Fix (버그 수정)

#136 [fix] 프로필 등록, 편집 페이지 버그 수정
  src/components/TextField.tsx
  src/hooks/useUserStore.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileRegisterPage.tsx
Labels: Bug Fix (버그 수정)

#138 [fix] 가게 정보 등록/편집 페이지 버그 수정
  src/constants/wage.ts
  src/pages/ShopEditPage.tsx
  src/pages/ShopRegisterPage.tsx
Labels: Bug Fix (버그 수정)

#139 [fix] 모달 컴포넌트 버그 수정
  src/components/Modal/AlertModalLayout.tsx
  src/components/Modal/Modal.tsx
Labels: Bug Fix (버그 수정)

#145 [fix] 내 가게 페이지 버그 수정
  src/components/Post/PostCard.tsx
  src/pages/ShopPage/ShopPage.tsx
Labels: Bug Fix (버그 수정)

#140 [fix] 공고 등록/편집 페이지 버그 수정
  src/pages/NoticeEditPage.tsx
  src/pages/NoticeRegisterPage.tsx
Labels: Bug Fix (버그 수정)

#147 [style] 상세 필터 버튼 스타일 수정
  src/components/Dropdown/FilterDropdownContent.tsx
Labels: UI/UX (스타일 변경)

#150 [fix] 공고 컴포넌트 수정
  src/utils/payRate.ts
Labels: Bug Fix (버그 수정)

#153 [fix] 상태에 따른 공고 버튼 문구 변경 로직 추가, 최근 본 공고 버그 수정
  src/apis/loaders/notice.ts
  src/components/NoticeDetailInfo/NoticeDetailInfo.tsx
  src/components/NoticeDetailInfo/NoticeEmployerActionButton.tsx
  src/pages/NoticeEmployeePage/NoticeEmployeePage.tsx
  src/pages/NoticeEmployeePage/loader/noticeEmployeeLoader.ts
  src/pages/NoticeEmployerPage/NoticeEmployerPage.tsx
  src/pages/NoticeEmployerPage/components/NoticeApplicationTableContainer.tsx
  src/pages/NoticeEmployerPage/hooks/useShopApplications.ts
  src/pages/NoticeEmployerPage/loader/noticeEmployerLoader.ts
Labels: Feature (기능 추가), Bug Fix (버그 수정)

#152 [fix] 내 가게 페이지 버그 수정
  src/pages/ShopPage/ShopPage.tsx
Labels: Bug Fix (버그 수정)

#156 [style] 프로필 페이지, 스켈레톤, Pagination 등 담당 작업 반응형 스타일 수정
  src/components/NoticeDetailSkeleton.tsx
  src/components/PageErrorElement.tsx
  src/components/Pagination.tsx
  src/pages/ProfilePage/components/UserApplicationTable.tsx
  src/pages/ProfilePage/components/UserApplicationTableSkeleton.tsx
Labels: Bug Fix (버그 수정), UI/UX (스타일 변경)

#158 [fix] 공고 상세 (사장님) 공고 편집 버튼 클릭 시, 페이지 이동 안되는 버그 수정
  src/components/NoticeDetailInfo/NoticeEmployerActionButton.tsx
Labels: Bug Fix (버그 수정)

#159 [fix] 프로필 페이지 로그아웃 시, 로그인 필요 모달이 뜨는 버그 수정, 불필요한 index.ts 파일 제거
  src/assets/shop/Image-light-1.webp
  src/assets/shop/Image-light-10.webp
  src/assets/shop/Image-light-11.webp
  src/assets/shop/Image-light-12.webp
  src/assets/shop/Image-light-13.webp
  src/assets/shop/Image-light-14.webp
  src/assets/shop/Image-light-15.webp
  src/assets/shop/Image-light-16.webp
  src/assets/shop/Image-light-17.webp
  src/assets/shop/Image-light-18.webp
  src/assets/shop/Image-light-2.webp
  src/assets/shop/Image-light-3.webp
  src/assets/shop/Image-light-4.webp
  src/assets/shop/Image-light-5.webp
  src/assets/shop/Image-light-6.webp
  src/assets/shop/Image-light-7.webp
  src/assets/shop/Image-light-8.webp
  src/assets/shop/Image-light-9.webp
  src/assets/shop/index.ts
  src/components/NoticeDetailInfo/NoticeDetailInfo.tsx
  src/components/NoticeDetailInfo/NoticeEmployeeActionButton.tsx
  src/components/ProtectedRoute.tsx
  src/components/Toast/ToastContainer.tsx
  src/components/Toast/ToastPortal.tsx
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useNoticeList.ts
  src/layouts/Header.tsx
  src/pages/AuthPage/SigninPage.tsx
  src/pages/AuthPage/SignupPage.tsx
  src/pages/NoticeEditPage.tsx
  src/pages/NoticeEmployeePage/loader/noticeEmployeeLoader.ts
  src/pages/NoticeEmployerPage/NoticeEmployerPage.tsx
  src/pages/NoticeEmployerPage/loader/noticeEmployerLoader.ts
  src/pages/NoticeListPage/NoticeListPage.tsx
  src/pages/NoticeRegisterPage.tsx
  src/pages/NoticeSearchPage/NoticeSearchPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfilePage/loader/profileLoader.ts
  src/pages/ProfileRegisterPage.tsx
  src/pages/ShopEditPage.tsx
  src/pages/ShopPage/ShopPage.tsx
  src/pages/ShopPage/hooks/useShopData.ts
  src/pages/ShopRegisterPage.tsx
  src/pages/index.ts
  src/store/index.ts
  src/store/useUserStore.ts
  src/store/useUserStore.tsx
  src/utils/index.ts
Labels: Bug Fix (버그 수정), Configuration (환경 설정)

#161 [fix] 공고 리스트 및 footer 버그 수정
  src/components/Dropdown/DropdownPopover.tsx
  src/components/Modal/AlertModalLayout.tsx
  src/components/Modal/ConfirmModalLayout.tsx
  src/components/Modal/Modal.tsx
  src/components/SearchInput.tsx
  src/layouts/Footer.tsx
  src/pages/NoticeListPage/NoticeListPage.tsx
  src/pages/NoticeListPage/TotalNoticeSection.tsx
Labels: Bug Fix (버그 수정)

#163 [fix] 공고 리스트 맞춤 공고 그림자 수정
  src/components/Post/PostListSlider.tsx
Labels: Bug Fix (버그 수정)

#166 [fix] 로그인, 회원가입 페이지 UI 및 버그 수정
  src/assets/landing/landing-img.webp
  src/assets/landing/logo-white.svg
  src/components/TextField.tsx
  src/index.css
  src/layouts/AuthLayout.tsx
  src/pages/AuthPage/SigninPage.tsx
  src/pages/AuthPage/SignupPage.tsx
Labels: Bug Fix (버그 수정), UI/UX (스타일 변경)

#169 [fix] 로그인/회원가입 페이지 롤백
  src/assets/landing/landing-img.webp
  src/assets/landing/logo-white.svg
  src/components/TextField.tsx
  src/index.css
  src/layouts/AuthLayout.tsx
  src/pages/AuthPage/SigninPage.tsx
  src/pages/AuthPage/SignupPage.tsx
Labels: UI/UX (스타일 변경)

#171 [fix] Modal 및 공고 리스트 페이지 인상률 버그 수정
  src/components/Modal/AlertModalLayout.tsx
  src/pages/NoticeListPage/CustomNoticeSection.tsx
Labels: Bug Fix (버그 수정)

#173 [fix] 상세 필터 페이지 이동 시에도 유지되는 버그 수정
  src/components/Alert/Alert.tsx
  src/components/Dropdown/FilterDropdownContent.tsx
  src/components/NoticeSearchResultHeader.tsx
  src/store/useFilterStore.ts
Labels: Bug Fix (버그 수정)
